site_name: NPAC
repo_url: https://github.com/npacore/npacore.github.io/
edit_uri: edit/main/docs/
theme:
  name: material
  custom_dir: docs
  logo: imgs/npac_correlationMatrix_BIDS.png
  favicon: imgs/npac_correlationMatrix_BIDS.png
  palette:
    - primary: teal
    - accent: red
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - content.code.annotate
    - content.action.edit
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite

plugins:
  - multirepo:
      cleanup: False # rm multirepo_docs/ with other repo docs
      keep_docs_dir: true
      #folder_name: multirepo_docs # where other repos are stored
      repos:
        - section: 'MRRC QA'
          section_path: 'Projects/External'
          import_url: 'https://github.com/NPACore/fw-mrrcqa?branch=main&docs_dir=*.md&multi_docs=false'
        - section: 'svslipid'
          section_path: 'Projects/External'
          import_url: 'https://github.com/NPACore/svslipid?branch=main&docs_dir=*.md&multi_docs=false'
        - section: ''
          section_path: 'Projects/External'
          import_url: 'https://github.com/NPACore/awesome-neuroimaging?branch=main&docs_dir=readme.md&multi_docs=true'

